// Generated by scripts/generate-font-metrics.mjs — do not edit by hand.
// Advance widths (+ ascent) of the eight bundled Text/TextBox `font:` faces
// (DESIGN.md §3.3 font: row, ◆41) — the TextBox wrap engine's per-font
// measuring stick, same encoding as geist-metrics.ts. Geist itself stays
// generated separately into geist-metrics.ts (unchanged format) because its
// renderer-side ascent is a hand-tuned constant, not hhea-derived — see
// cardSvg.tsx's ascentOf for the documented inconsistency.
// Encoding: "<codepoint delta base36>.<advance base36>" entries joined by ",",
// codepoints ascending — decoded into a Map at module load (one shared
// decode() rather than one per face).

/** One face's measuring stick — the same three fields as geist-metrics.ts's
 * exports, plus `ascent` (hhea ascender ÷ unitsPerEm) for baseline
 * realization (cardSvg.tsx), which Geist deliberately does not get here. */
export interface GeneratedFontMetrics {
  unitsPerEm: number;
  /** Mean advance over the covered codepoints — charged for uncovered chars. */
  fallbackAdvance: number;
  /** BMP codepoint → advance width in font units. */
  advances: ReadonlyMap<number, number>;
  /** hhea ascender / unitsPerEm. */
  ascent: number;
}

/** The eight ◆41 face tokens this module covers (mirrors the non-"geist"
 * subset of model.ts's FONT_FACES — pinned by a test, since a generated file
 * imports nothing by convention, geist-metrics.ts included). */
export type BundledFontFace =
  | "garamond"
  | "garamond_bold"
  | "garamond_italic"
  | "garamond_bold_italic"
  | "courier"
  | "courier_bold"
  | "courier_italic"
  | "courier_bold_italic";

function decode(packed: string): ReadonlyMap<number, number> {
  const map = new Map<number, number>();
  let cp = 0;
  for (const entry of packed.split(",")) {
    const dot = entry.indexOf(".");
    cp += parseInt(entry.slice(0, dot), 36);
    map.set(cp, parseInt(entry.slice(dot + 1), 36));
  }
  return map;
}

const GARAMOND_PACKED =
  "w.6i,1.6v,1.7v,1.em,1.bf,1.fy,1.jd,1.3w,1.8l,1.8l,1.cg,1.b2,1.66,1.8z,1.5h,1.9h,1.d9,1.98,1.b6,1.at," +
  "1.cj,1.bd,1.cx,1.bx,1.dl,1.cx,1.5h,1.68,1.bb,1.d0,1.bb,1.95,1.jz,1.ji,1.fi,1.j2,1.j7,1.ex,1.e5,1.jt," +
  "1.l3,1.98,1.8y,1.i2,1.et,1.n7,1.k7,1.la,1.f3,1.la,1.ip,1.dn,1.hm,1.je,1.ii,1.pv,1.i4,1.gx,1.gj,1.7m," +
  "1.9h,1.7m,1.aw,1.b2,1.5x,1.bn,1.e6,1.bf,1.e8,1.bc,1.8h,1.cd,1.dv,1.7l,1.75,1.dn,1.76,1.l7,1.ed,1.db," +
  "1.e7,1.dk,1.a4,1.9e,1.9e,1.dp,1.c2,1.in,1.c7,1.c3,1.b9,1.81,1.4o,1.7v,1.cb,y.6i,1.6v,1.ey,1.c0,1.bi," +
  "1.dd,1.4o,1.c9,1.8y,1.jz,1.7q,1.co,1.az,1.go,1.ku,1.9l,1.98,1.b2,1.6z,1.6z,1.5w,2.hr,1.5f,1.6g,1.7a," +
  "1.8r,1.co,1.go,1.gy,1.gd,1.93,1.ji,1.ji,1.ji,1.ji,1.ji,1.ji,1.oa,1.j2,1.ex,1.ex,1.ex,1.ex,1.98,1.98," +
  "1.98,1.98,1.j7,1.k7,1.la,1.la,1.la,1.la,1.la,1.am,1.lf,1.je,1.je,1.je,1.je,1.gx,1.ey,1.e5,1.bn,1.bn," +
  "1.bn,1.bn,1.bn,1.bn,1.gg,1.bf,1.bc,1.bc,1.bc,1.bc,1.7l,1.7l,1.7l,1.7l,1.d2,1.ed,1.db,1.db,1.db,1.db," +
  "1.db,1.b2,1.d9,1.dp,1.dp,1.dp,1.dp,1.c3,1.dn,1.c3,1.ji,1.bn,1.ji,1.bn,1.jk,1.bn,1.j2,1.bf,1.j2,1.bf," +
  "1.j2,1.bf,1.j2,1.bf,1.j7,1.e8,1.j7,1.e9,1.ex,1.bc,1.ex,1.bc,1.ex,1.bc,1.ex,1.bc,1.ex,1.bc,1.jt,1.cd," +
  "1.jt,1.cd,1.jt,1.cd,1.jt,1.cd,1.l3,1.dv,1.l3,1.dv,1.98,1.7l,1.98,1.7l,1.98,1.7l,1.98,1.7l,1.98,1.7l," +
  "1.j6,1.em,1.8y,1.75,1.i2,1.dn,1.e5,1.et,1.76,1.et,1.76,1.et,1.76,1.et,1.76,1.ej,1.7a,1.k7,1.ed,1.k7," +
  "1.ed,1.k7,1.ed,1.ed,1.k7,1.e0,1.la,1.db,1.la,1.db,1.la,1.db,1.pe,1.jb,1.ip,1.a4,1.ip,1.a4,1.ip,1.a4," +
  "1.dn,1.9e,1.dn,1.9e,1.dn,1.9e,1.dn,1.9e,1.hm,1.9e,1.hm,1.9e,1.hk,1.9f,1.je,1.dp,1.je,1.dp,1.je,1.dp," +
  "1.je,1.dp,1.je,1.dp,1.je,1.dp,1.pv,1.in,1.gx,1.c3,1.gx,1.gj,1.b9,1.gj,1.b9,1.gj,1.b9,1.7b,g.ib,3.9a," +
  "5.98,9.la,1.db,e.je,1.dt,t.ji,1.bn,1.98,1.7l,1.la,1.db,1.je,1.dp,1.je,1.dp,1.je,1.dp,1.je,1.dp,1.je," +
  "1.dp,6.oa,1.gg,3.ju,1.cd,1.i2,1.dn,1.la,1.db,d.k7,1.ed,1.ji,1.bn,1.oa,1.gg,1.lf,1.d9,1.ji,1.bn,1.ji," +
  "1.bn,1.ex,1.bc,1.ex,1.bc,1.98,1.7l,1.98,1.7l,1.la,1.db,1.la,1.db,1.ip,1.a4,1.ip,1.a4,1.je,1.dp,1.je," +
  "1.dp,1.dn,1.9e,1.hm,1.9e,n.gx,1.c3,4.75,d.je,d.dm,8.b9,8.cy,7.7l,x.dp,1e.5x,1.4k,2.5d,1.5g,7.75,1.6p" +
  ",1.65,2.7n,1.7m,1.66,c.7n,1.42,1.8l,1.7g,1.ao,1.8h,z.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1" +
  ".0,2.0,2.0,a.0,8.0,1.0,2.0,1.0,1.0,5.0,1.0,3.0,u.0,9.0,1o.jf,l.jx,j.dz,4.dm,1s.ex,1.ex,1.kg,1.e9,1.i" +
  "l,1.dn,1.98,1.98,1.8p,1.ox,1.rd,1.jz,1.i9,1.ld,1.gz,1.k4,1.ji,1.fi,1.fi,1.e9,1.jq,1.ex,1.rj,1.dy,1.l" +
  "d,1.ld,1.i9,1.ji,1.n7,1.l3,1.la,1.kl,1.f3,1.il,1.hm,1.gz,1.lf,1.i4,1.k8,1.hf,1.sl,1.su,1.i8,1.nn,1.f" +
  "4,1.hi,1.ss,1.gi,1.bn,1.d6,1.c5,1.ac,1.d5,1.bc,1.ib,1.a9,1.e7,1.e7,1.cs,1.ck,1.fm,1.ec,1.db,1.ec,1.e" +
  "1,1.bf,1.br,1.c3,1.hq,1.c7,1.e8,1.bu,1.kj,1.ki,1.ct,1.hm,1.be,1.ce,1.iz,1.bp,1.bc,1.bc,1.d1,1.ac,1.b" +
  "f,1.9e,1.7l,1.7l,1.75,1.ga,1.iv,1.dv,1.cs,1.e7,1.c3,1.ec,3.i7,1.cs,7.pt,1.ib,7.la,1.db,1.io,1.ca,l.l" +
  "d,1.ec,1.f4,1.be,1.f3,1.e1,1.e0,1.a7,1.e9,1.ac,1.gv,1.bg,1.rj,1.il,1.dy,1.9v,1.i9,1.cy,1.ji,1.dx,1.i" +
  "9,1.ct,1.l3,1.ef,1.l3,1.ec,1.om,1.ht,3.lx,1.e4,1.il,1.bf,1.hm,1.br,1.gx,1.c2,1.gx,1.c2,1.hz,1.c7,1.o" +
  "4,1.gr,1.hf,1.bj,1.hr,1.ch,1.he,1.dv,1.kk,1.db,1.kk,1.db,1.98,1.rj,1.ib,1.hv,1.cq,1.ji,1.ck,1.la,1.e" +
  "6,1.l3,1.ec,1.hf,1.bq,1.n7,1.fm,1.76,1.ji,1.bn,1.ji,1.bn,1.oa,1.gg,1.ex,1.bc,1.hs,1.b9,1.hs,1.b9,1.r" +
  "j,1.ib,1.dy,1.a9,1.ea,1.b6,1.ld,1.e7,1.ld,1.e7,1.la,1.db,1.la,1.db,1.la,1.db,1.hi,1.ce,1.gz,1.c3,1.g" +
  "z,1.c3,1.gz,1.c3,1.hf,1.bu,1.e9,1.ac,1.nn,1.hm,1.e9,1.ac,1.i4,1.c7,1.i4,1.c7,h.dy,1.9x,1.iu,1.cy,7.l" +
  "a,1.dk,1.pv,1.in,7.kl,1.ec,1.he,1.dv,1.lm,1.ec,5.in,1.cy,1sg.du,31t.98,2k.j7,1.e8,1.j7,1.e8,h.ju,1.c" +
  "d,3.l3,1.dv,5.l3,1.dv,5.i2,1.dn,5.et,1.76,1.et,1.76,1.et,1.76,3.n7,1.l7,1.n7,1.l7,1.n7,1.l7,1.k7,1.e" +
  "d,1.k7,1.ed,1.k7,1.ed,1.k7,1.ed,f.ip,1.a4,1.ip,1.a4,1.ip,1.a4,1.dn,1.9e,1.dn,1.9e,9.hm,1.9e,1.hm,1.9" +
  "e,h.pv,1.in,1.pv,1.in,1.pv,1.in,9.gx,1.c3,3.gj,1.b9,4.9e,7.in,2.ji,1.bn,1.ji,1.bn,1.ji,1.bn,1.ji,1.b" +
  "n,1.ji,1.bn,1.ji,1.bn,1.ji,1.bn,1.ji,1.bn,1.ji,1.bn,1.ji,1.bn,1.ji,1.bn,1.ji,1.bn,1.ex,1.bc,1.ex,1.b" +
  "c,1.ex,1.bc,1.ex,1.bc,1.ex,1.bc,1.ex,1.bc,1.ex,1.bc,1.ex,1.bc,1.98,1.7l,1.98,1.7l,1.la,1.db,1.la,1.d" +
  "b,1.la,1.db,1.la,1.db,1.la,1.db,1.la,1.db,1.la,1.db,1.la,1.db,1.la,1.db,1.la,1.db,1.la,1.db,1.la,1.d" +
  "b,1.je,1.dp,1.je,1.dp,1.je,1.dt,1.je,1.dt,1.je,1.dt,1.je,1.dt,1.je,1.dt,1.gx,1.c3,1.gx,1.c3,1.gx,1.c" +
  "3,1.gx,1.c3,7b.eb,1.n2,1.dx,1.rt,1.99,1.6y,1.4n,1.c8,1.88,1.5k,1.39,1.go,1.go,1.go,3.8z,1.8z,1.dn,1." +
  "eb,1.n2,1.hk,3.5e,1.5c,1.5c,2.9g,1.9g,1.9i,2.9e,1.9e,1.8i,4.ih,1.5f,1.go,1.go,6.5k,1.nt,2.3w,1.7n,6." +
  "8g,1.8g,8.nt,1.d0,1.2p,r.66,1.go,3.go,d.89,4.7c,1.70,1.7o,1.6q,1.7o,1.83,1.b2,3.49,1.49,1.8y,1.89,1." +
  "7a,1.6z,1.6z,1.7c,1.70,1.7o,1.6q,1.7o,1.83,4.49,1.49,j.ey,3.c0,2.fu,1.dh,3.et,1.ct,1.gb,2.ds,3.dh,1." +
  "fh,2.cc,1.ey,3.e3,1.bs,1.c6,3.cr,2e.b0,3.o2,1.ku,9.i2,2.k0,c.ds,19.hn,1.hc,1.hd,1.h3,1e.i6,1.c3,1.i1" +
  ",1.c3,1.ka,1.c3,1.dc,1.dc,1.dc,1.dc,2x.ed,3.g3,a.js,2.ez,1.b2,8.c1,4.ms,d.7x,t.e9,o.d0,4.bc,1.bc,mz." +
  "8e,1.8e,h.gz,1.h1,3.gz,1.gz,5.gz,1.h1,3.gz,1.gz,5.8e,1.8e,3.8e,1.lb,4.lb,n.8d,l.gz,1.gz,w.u3,2.uc,s." +
  "lu,8c.jr,qd.la,1.lb,ys.rs,njd.fn,2q.6v,1.5r,h9v.go,6y.go,1.go,1.go";

const GARAMOND_BOLD_PACKED =
  "w.6i,1.7b,1.8e,1.em,1.bq,1.fy,1.jw,1.46,1.8l,1.8l,1.cg,1.b2,1.66,1.8z,1.5r,1.9r,1.d9,1.98,1.b6,1.ay," +
  "1.co,1.bd,1.cx,1.bx,1.dl,1.cx,1.5r,1.6g,1.bb,1.d0,1.bb,1.9f,1.k9,1.jw,1.gj,1.ix,1.jl,1.fc,1.ei,1.kb," +
  "1.l8,1.9i,1.9f,1.i7,1.f5,1.nt,1.kf,1.la,1.fd,1.la,1.je,1.eb,1.hv,1.jj,1.ic,1.pb,1.hz,1.h7,1.gt,1.7m," +
  "1.9r,1.7m,1.aw,1.b2,1.5x,1.bp,1.ec,1.bt,1.e6,1.bm,1.8h,1.cj,1.e5,1.7b,1.7b,1.dn,1.7g,1.ll,1.em,1.dl," +
  "1.e9,1.dy,1.aj,1.9d,1.9c,1.e1,1.c8,1.j1,1.c8,1.bv,1.b9,1.81,1.4o,1.7v,1.cb,y.6i,1.7b,1.eq,1.c0,1.bi," +
  "1.du,1.4o,1.dk,1.8y,1.k7,1.80,1.d7,1.az,1.go,1.kk,1.9l,1.98,1.b2,1.71,1.6z,1.5w,2.i9,1.5f,1.6g,1.7a," +
  "1.91,1.d7,1.gv,1.h0,1.gk,1.93,1.jw,1.jw,1.jw,1.jw,1.jw,1.jw,1.oo,1.ix,1.fc,1.fc,1.fc,1.fc,1.9i,1.9i," +
  "1.9i,1.9i,1.jl,1.kf,1.la,1.la,1.la,1.la,1.la,1.b3,1.lx,1.jj,1.jj,1.jj,1.jj,1.h7,1.f9,1.g3,1.bp,1.bp," +
  "1.bp,1.bp,1.bp,1.bp,1.gd,1.bt,1.bm,1.bm,1.bm,1.bm,1.7b,1.7b,1.7b,1.7b,1.d2,1.em,1.dl,1.dl,1.dl,1.dl," +
  "1.dl,1.b2,1.d9,1.e1,1.e1,1.e1,1.e1,1.bv,1.ds,1.bv,1.jw,1.bp,1.jw,1.bp,1.jw,1.bp,1.ix,1.bt,1.ix,1.bt," +
  "1.ix,1.bt,1.ix,1.bt,1.jl,1.e6,1.jl,1.e7,1.fc,1.bm,1.fc,1.bm,1.fc,1.bm,1.fc,1.bm,1.fc,1.bm,1.kb,1.cj," +
  "1.kb,1.cj,1.kb,1.cj,1.kb,1.cj,1.l8,1.e5,1.l8,1.e5,1.9i,1.7b,1.9i,1.7b,1.9i,1.7b,1.9i,1.7b,1.9i,1.7b," +
  "1.jf,1.es,1.9f,1.7b,1.i7,1.dn,1.e5,1.f5,1.7g,1.f5,1.7g,1.f5,1.7g,1.f5,1.7g,1.f5,1.7j,1.kf,1.em,1.kf," +
  "1.em,1.kf,1.em,1.em,1.kf,1.e5,1.la,1.dl,1.la,1.dl,1.la,1.dl,1.pw,1.j5,1.je,1.aj,1.je,1.aj,1.je,1.aj," +
  "1.eb,1.9d,1.eb,1.9d,1.eb,1.9d,1.eb,1.9d,1.hv,1.9c,1.hv,1.9c,1.hk,1.9f,1.jj,1.e1,1.jj,1.e1,1.jj,1.e1," +
  "1.jj,1.e1,1.jj,1.e1,1.jj,1.e1,1.pb,1.j1,1.h7,1.bv,1.h7,1.gt,1.b9,1.gt,1.b9,1.gt,1.b9,1.79,g.iu,3.9s," +
  "5.9i,9.la,1.dl,e.jj,1.e4,t.jw,1.bp,1.9i,1.7b,1.la,1.dl,1.jj,1.e1,1.jj,1.e1,1.jj,1.e1,1.jj,1.e1,1.jj," +
  "1.e1,6.oo,1.gd,3.jz,1.cj,1.i7,1.dn,1.la,1.dl,d.kf,1.em,1.jw,1.bp,1.oo,1.gd,1.lx,1.d9,1.jw,1.bp,1.jw," +
  "1.bp,1.fc,1.bm,1.fc,1.bm,1.9i,1.7b,1.9i,1.7b,1.la,1.dl,1.la,1.dl,1.je,1.aj,1.je,1.aj,1.jj,1.e1,1.jj," +
  "1.e1,1.eb,1.9d,1.hv,1.9c,n.h7,1.bv,4.7b,d.jj,d.dm,8.bl,8.d1,7.7b,x.e1,1e.63,1.4y,2.5m,1.5g,7.6n,1.5o" +
  ",1.65,2.7n,1.7m,1.69,c.7n,1.42,1.8l,1.7g,1.ao,1.8h,z.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1" +
  ".0,2.0,2.0,a.0,8.0,1.0,2.0,1.0,1.0,5.0,1.0,3.0,u.0,9.0,1o.jh,l.jy,j.dx,4.dm,1s.fc,1.fc,1.l2,1.em,1.i" +
  "l,1.eb,1.9i,1.9i,1.8v,1.q3,1.rz,1.kp,1.ij,1.l9,1.hd,1.kd,1.jw,1.gj,1.gj,1.em,1.jz,1.fc,1.s6,1.f3,1.l" +
  "9,1.l9,1.ij,1.jw,1.nt,1.l8,1.la,1.kv,1.fd,1.il,1.hv,1.hd,1.lx,1.hz,1.kf,1.hp,1.tn,1.to,1.it,1.ol,1.g" +
  "2,1.i0,1.t3,1.ha,1.bp,1.dj,1.cn,1.ae,1.d5,1.bm,1.jr,1.ay,1.eb,1.eb,1.d9,1.c7,1.fr,1.ev,1.dl,1.ev,1.e" +
  "2,1.bt,1.bk,1.bv,1.ik,1.c8,1.ep,1.ch,1.l5,1.l3,1.dn,1.j3,1.c3,1.co,1.js,1.c1,1.bm,1.bm,1.df,1.ae,1.b" +
  "t,1.9d,1.7b,1.7b,1.7b,1.gi,1.jk,1.e5,1.d9,1.eb,1.bv,1.er,3.jm,1.dg,7.or,1.il,7.la,1.dl,1.iw,1.cs,l.l" +
  "9,1.ev,1.g2,1.c3,1.fd,1.e2,1.er,1.ae,1.em,1.ae,1.hm,1.c1,1.s6,1.jw,1.f3,1.ab,1.ij,1.dc,1.ji,1.eb,1.i" +
  "j,1.dc,1.lb,1.f7,1.l7,1.et,1.ov,1.hv,3.lx,1.ew,1.il,1.bt,1.hv,1.bk,1.h7,1.c8,1.h7,1.c8,1.hz,1.c8,1.o" +
  "6,1.gw,1.hp,1.c7,1.i1,1.d3,1.ho,1.e5,1.kk,1.d2,1.kk,1.d2,1.9i,1.s6,1.jr,1.ij,1.d0,1.jw,1.c7,1.lh,1.e" +
  "q,1.l8,1.ev,1.hp,1.c7,1.nt,1.fr,1.7g,1.jw,1.bp,1.jw,1.bp,1.oo,1.gd,1.fc,1.bm,1.hr,1.bk,1.hr,1.bk,1.s" +
  "6,1.jr,1.f3,1.ay,1.fe,1.ay,1.l9,1.eb,1.l9,1.eb,1.la,1.dl,1.la,1.dl,1.la,1.dl,1.i0,1.co,1.hd,1.bv,1.h" +
  "d,1.bv,1.hd,1.bv,1.hp,1.ch,1.em,1.ae,1.ol,1.j3,1.em,1.ae,1.hz,1.c8,1.hz,1.c8,h.f3,1.am,1.jc,1.d6,7.l" +
  "a,1.dy,1.pb,1.j1,7.kv,1.ev,1.ho,1.e5,1.lq,1.ev,5.j3,1.d6,1sg.el,31t.98,2k.jl,1.e6,1.jl,1.e6,h.jz,1.c" +
  "j,3.l8,1.e5,5.l8,1.e5,5.i7,1.dn,5.f5,1.7g,1.f5,1.7g,1.f5,1.7g,3.nt,1.ll,1.nt,1.ll,1.nt,1.ll,1.kf,1.e" +
  "m,1.kf,1.em,1.kf,1.em,1.kf,1.em,f.je,1.aj,1.je,1.aj,1.je,1.aj,1.eb,1.9d,1.eb,1.9d,9.hv,1.9c,1.hv,1.9" +
  "c,h.pb,1.j1,1.pb,1.j1,1.pb,1.j1,9.h7,1.bv,3.gt,1.b9,4.9c,7.j2,2.jw,1.bp,1.jw,1.bp,1.jw,1.bp,1.jw,1.b" +
  "p,1.jw,1.bp,1.jw,1.bp,1.jw,1.bp,1.jw,1.bp,1.jw,1.bp,1.jw,1.bp,1.jw,1.bp,1.jw,1.bp,1.fc,1.bm,1.fc,1.b" +
  "m,1.fc,1.bm,1.fc,1.bm,1.fc,1.bm,1.fc,1.bm,1.fc,1.bm,1.fc,1.bm,1.9i,1.7b,1.9i,1.7b,1.la,1.dl,1.la,1.d" +
  "l,1.la,1.dl,1.la,1.dl,1.la,1.dl,1.la,1.dl,1.la,1.dl,1.la,1.dl,1.la,1.dl,1.la,1.dl,1.la,1.dl,1.la,1.d" +
  "l,1.jj,1.e1,1.jj,1.e1,1.jj,1.e4,1.jj,1.e4,1.jj,1.e4,1.jj,1.e4,1.jj,1.e4,1.h7,1.bv,1.h7,1.bv,1.h7,1.b" +
  "v,1.h7,1.bv,7b.eb,1.n2,1.dx,1.rt,1.99,1.6y,1.4n,1.6i,1.ji,1.5k,1.39,1.go,1.go,1.go,3.8z,1.8z,1.dn,1." +
  "eb,1.n2,1.hk,3.58,1.56,1.56,2.9z,1.9z,1.ab,2.9e,1.9e,1.90,4.ir,1.5f,1.go,1.go,6.5k,1.o3,2.46,1.8f,6." +
  "8g,1.8g,8.nt,1.dw,1.2p,r.66,1.go,3.go,d.89,4.7j,1.7a,1.7o,1.6q,1.7o,1.7o,1.b2,3.4j,1.4j,1.9l,1.89,1." +
  "7a,1.71,1.6z,1.7j,1.7a,1.7o,1.6q,1.7o,1.7o,4.4j,1.4j,j.eq,3.c0,2.fo,1.dr,3.g1,1.dn,1.gb,2.dy,3.dr,1." +
  "fb,2.c2,1.eq,3.dz,1.bn,1.c1,3.d3,2e.bi,3.nx,1.kk,9.ig,2.ki,c.ds,19.hn,1.hc,1.hn,1.h3,1e.i1,1.c3,1.i1" +
  ",1.c3,1.ka,1.c3,1.dc,1.dc,1.dc,1.dc,2x.em,3.g3,a.jm,2.f3,1.b2,8.c1,4.ms,d.7x,t.e9,o.d0,4.bc,1.bc,mz." +
  "8e,1.8e,h.gz,1.gz,3.gz,1.gz,5.gz,1.gz,3.gz,1.gz,5.8e,1.8e,3.8e,1.lb,4.lb,n.8d,l.gz,1.gz,w.uc,2.uc,s." +
  "my,8c.jr,qd.la,1.lb,ys.rs,njd.gq,2q.7b,1.67,h9v.go,6y.go,1.go,1.go";

const GARAMOND_ITALIC_PACKED =
  "0.go,d.6i,j.6i,1.63,1.8v,1.c3,1.ae,1.ef,1.kv,1.3l,1.7s,1.7s,1.cg,1.b2,1.68,1.8h,1.5h,1.8h,1.c6,1.83," +
  "1.a3,1.9i,1.br,1.ae,1.bo,1.ar,1.c8,1.bo,1.5h,1.66,1.bb,1.d0,1.bb,1.87,1.jz,1.go,1.eh,1.ga,1.h0,1.ea," +
  "1.df,1.hj,1.in,1.8k,1.7s,1.gj,1.ds,1.kc,1.i3,1.i3,1.dz,1.i3,1.h1,1.cu,1.fd,1.h6,1.gh,1.mv,1.g3,1.ep," +
  "1.f7,1.6w,1.8h,1.6w,1.9t,1.a3,1.4m,1.c2,1.c2,1.9l,1.cc,1.9j,1.7a,1.aj,1.cd,1.6v,1.6n,1.bl,1.6l,1.is," +
  "1.cx,1.b2,1.bb,1.bj,1.9g,1.8e,1.87,1.cx,1.c0,1.h6,1.bp,1.cb,1.9k,1.79,1.48,1.79,1.cb,y.6i,1.64,1.dl," +
  "1.as,1.af,1.c1,1.48,1.au,1.7n,1.k5,1.7o,1.bs,1.b1,1.8h,1.l6,1.99,1.8b,1.b2,1.6c,1.6c,1.5w,2.gi,1.5k," +
  "1.5g,1.6l,1.7h,1.br,1.f8,1.fn,1.f0,1.8g,1.go,1.go,1.go,1.go,1.go,1.go,1.ld,1.ga,1.ea,1.ea,1.ea,1.ea," +
  "1.8k,1.8k,1.8k,1.8k,1.h0,1.i3,1.i3,1.i3,1.i3,1.i3,1.i3,1.b2,1.i3,1.h6,1.h6,1.h6,1.h6,1.ep,1.eu,1.cg," +
  "1.c2,1.c2,1.c2,1.c2,1.c2,1.c2,1.f1,1.9l,1.9j,1.9j,1.9j,1.9j,1.6v,1.6v,1.6v,1.6v,1.b5,1.cx,1.b2,1.b2," +
  "1.b2,1.b2,1.b2,1.aq,1.bc,1.cx,1.cx,1.cx,1.cx,1.cb,1.bd,1.cb,1.go,1.c2,1.go,1.c2,1.go,1.c3,1.ga,1.9l," +
  "1.ga,1.9l,1.ga,1.9l,1.ga,1.9l,1.h0,1.cc,1.h0,1.c4,1.ea,1.9j,1.ea,1.9j,1.ea,1.9j,1.ea,1.9o,1.ea,1.9j," +
  "1.hj,1.aj,1.hj,1.aj,1.hj,1.aj,1.hj,1.aj,1.in,1.cd,1.in,1.cb,1.8k,1.6v,1.8k,1.6v,1.8k,1.6v,1.8k,1.6v," +
  "1.8k,1.6v,1.h7,1.cj,1.7s,1.6n,1.gj,1.bl,1.c3,1.ds,1.6l,1.ds,1.6l,1.ds,1.6l,1.ds,1.6l,1.ds,1.6x,1.i3," +
  "1.cx,1.i3,1.cx,1.i3,1.cx,1.cx,1.i3,1.c1,1.i3,1.b2,1.i3,1.b2,1.i3,1.b2,1.mf,1.h0,1.h1,1.9g,1.h1,1.9g," +
  "1.h1,1.9g,1.cu,1.8e,1.cu,1.8e,1.cu,1.8e,1.cu,1.8e,1.fd,1.87,1.fd,1.87,1.fd,1.86,1.h6,1.cx,1.h6,1.cx," +
  "1.h6,1.cx,1.h6,1.cx,1.h6,1.cx,1.h6,1.cy,1.mv,1.h6,1.ep,1.cb,1.ep,1.f7,1.9k,1.f7,1.9k,1.f7,1.9k,1.6g," +
  "g.gf,3.7a,5.8k,9.i3,1.b2,e.h5,1.d9,t.go,1.c2,1.8k,1.6v,1.i3,1.b2,1.h6,1.cx,1.h6,1.cx,1.h6,1.cx,1.h6," +
  "1.cx,1.h6,1.cx,6.ld,1.f1,3.hj,1.aj,1.gj,1.bl,1.i3,1.b2,d.i3,1.cx,1.go,1.c2,1.ld,1.f1,1.i3,1.bc,1.go," +
  "1.c2,1.go,1.c2,1.ea,1.9j,1.ea,1.9j,1.8k,1.6v,1.8k,1.6v,1.i3,1.b2,1.i3,1.b2,1.h1,1.9g,1.h1,1.9g,1.h6," +
  "1.cx,1.h6,1.cx,1.cu,1.8e,1.fd,1.87,n.ep,1.cb,4.6n,d.h6,d.c2,8.9v,8.bd,7.6v,x.cx,1e.5x,1.45,2.5d,1.5g" +
  ",7.6n,1.66,3.7n,1.6v,d.6i,1.42,1.6x,1.6c,1.7l,1.7y,z.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1" +
  ".0,2.0,2.0,a.0,8.0,1.0,2.0,1.0,1.0,5.0,1.0,3.0,u.0,9.0,1o.hf,l.hy,j.ca,4.c8,1s.ea,1.ea,1.ib,1.d5,1.g" +
  "a,1.cu,1.8k,1.8k,1.7s,1.mi,1.oo,1.il,1.gj,1.j7,1.fj,1.is,1.go,1.dy,1.eh,1.d5,1.hy,1.ea,1.oy,1.cq,1.j" +
  "7,1.j7,1.gj,1.hj,1.kc,1.in,1.i3,1.j2,1.dz,1.ga,1.fd,1.fj,1.je,1.g3,1.is,1.g7,1.qf,1.qd,1.ge,1.m8,1.d" +
  "q,1.fm,1.q1,1.f2,1.c2,1.bs,1.b4,1.91,1.bg,1.9j,1.il,1.99,1.cx,1.cx,1.cd,1.ce,1.fn,1.d2,1.b2,1.cx,1.b" +
  "b,1.9l,1.is,1.cb,1.fx,1.bp,1.cw,1.bq,1.is,1.ir,1.ah,1.ft,1.ai,1.af,1.gd,1.b5,1.9j,1.9j,1.bo,1.91,1.9" +
  "l,1.8e,1.6v,1.6v,1.6n,1.g7,1.gx,1.cb,1.cd,1.cx,1.cb,1.cx,3.ge,1.gh,7.nd,1.gs,7.i3,1.bc,1.h0,1.c1,l.j" +
  "a,1.cx,1.dq,1.9z,1.dz,1.bb,1.cm,1.98,1.d5,1.91,1.f6,1.aw,1.oy,1.il,1.cq,1.99,1.gu,1.ce,1.i6,1.d9,1.g" +
  "j,1.bs,1.jm,1.da,1.jn,1.d4,1.ma,1.fd,3.k2,1.ct,1.ga,1.9l,1.fd,1.is,1.ep,1.bp,1.ep,1.bp,1.gb,1.bp,1.l" +
  "o,1.cx,1.g6,1.bq,1.g7,1.c4,1.fs,1.cd,1.ik,1.bx,1.ik,1.bx,1.8k,1.oy,1.il,1.gj,1.ca,1.go,1.ce,1.ic,1.c" +
  "q,1.in,1.d2,1.g6,1.bq,1.kc,1.ft,1.6l,1.go,1.c2,1.go,1.c2,1.ld,1.f1,1.ea,1.9j,1.gf,1.9v,1.gf,1.9v,1.o" +
  "y,1.il,1.cq,1.99,1.d7,1.a2,1.j7,1.cx,1.j7,1.cx,1.i3,1.b2,1.i3,1.b2,1.i3,1.b2,1.fm,1.af,1.fj,1.cb,1.f" +
  "j,1.cb,1.fj,1.cb,1.g7,1.bq,1.d5,1.91,1.m8,1.ft,1.d5,1.9t,1.g3,1.bp,1.g3,1.bp,h.ck,1.94,1.gz,1.bx,7.i" +
  "3,1.bj,1.mv,1.h6,7.j2,1.cx,1.gd,1.cd,1.io,1.dg,5.h6,1.ce,1sg.du,34d.h0,1.cc,1.h0,1.cc,h.hj,1.aj,3.in" +
  ",1.cd,5.in,1.cd,5.gj,1.bl,5.ds,1.6l,1.ds,1.6l,1.ds,1.6l,3.kc,1.is,1.kc,1.is,1.kc,1.is,1.i3,1.cx,1.i3" +
  ",1.cx,1.i3,1.cx,1.i3,1.cx,f.h1,1.9g,1.h1,1.9g,1.h1,1.9g,1.cu,1.8e,1.cu,1.8e,9.fd,1.87,1.fd,1.87,h.mv" +
  ",1.h6,1.mv,1.h6,1.mv,1.h6,9.ep,1.cb,3.f7,1.9k,4.87,7.gd,2.go,1.c2,1.go,1.c2,1.go,1.c2,1.go,1.c2,1.go" +
  ",1.c2,1.go,1.c2,1.go,1.c2,1.go,1.c2,1.go,1.c2,1.go,1.c2,1.go,1.c2,1.go,1.c2,1.ea,1.9j,1.ea,1.9j,1.ea" +
  ",1.9j,1.ea,1.9j,1.ea,1.9j,1.ea,1.9j,1.ea,1.9j,1.ea,1.9j,1.8k,1.6v,1.8k,1.6v,1.i3,1.b2,1.i3,1.b2,1.i3" +
  ",1.b2,1.i3,1.b2,1.i3,1.b2,1.i3,1.b2,1.i3,1.b2,1.i3,1.b2,1.i3,1.b2,1.i3,1.b2,1.i3,1.b2,1.i3,1.b2,1.h6" +
  ",1.cx,1.h6,1.cx,1.h5,1.d9,1.h5,1.d9,1.h5,1.d9,1.h5,1.d9,1.h5,1.d9,1.ep,1.cb,1.ep,1.cb,1.ep,1.cb,1.ep" +
  ",1.cb,7b.eb,1.n2,1.dx,1.rt,1.99,1.6y,1.4n,1.dn,1.88,1.5k,1.39,1.go,1.go,1.go,3.8h,1.8h,1.dn,1.eb,1.n" +
  "2,4.54,1.54,1.4v,2.95,1.95,1.95,2.9c,1.ak,1.8f,4.ih,1.5k,1.go,1.go,6.5k,1.l9,2.3w,1.7n,6.7p,1.7o,8.n" +
  "s,1.bx,1.2p,r.66,1.go,3.go,d.7i,4.6l,1.6d,1.6w,1.64,1.6w,1.7d,1.b2,3.46,1.46,1.86,1.7i,1.6l,1.6c,1.6" +
  "c,1.6l,1.6d,1.6w,1.64,1.6w,1.7d,4.46,1.46,j.dl,3.as,2.e8,1.c5,3.et,1.bk,1.ei,2.cf,3.c5,1.e1,2.b4,1.d" +
  "l,3.co,1.an,1.ay,3.b3,2e.9x,3.l5,1.ku,9.hn,2.k0,c.ds,19.g6,1.fx,1.fy,1.fp,1e.i6,1.c3,1.i1,1.c3,1.ka," +
  "1.c3,1.dc,1.dc,1.dc,1.dc,2x.cv,3.c4,a.jz,2.gi,1.b2,8.c1,4.kk,d.7a,t.e9,o.d0,4.ba,1.bc,mz.8e,1.8e,h.g" +
  "z,1.h1,3.gz,1.gz,5.gz,1.h1,3.gz,1.gz,5.8e,1.8e,3.8e,1.lb,4.lb,n.8d,l.gz,1.gz,w.u1,2.uc,s.lx,8c.jr,qd" +
  ".la,1.lb,ys.rs,njd.e1,2q.6v,1.5r,ghg.e5,1.cx,1.dq,1.js,1.kl,1.eo,1.gf,s9.go,6y.go,1.go,1.go";

const GARAMOND_BOLD_ITALIC_PACKED =
  "0.go,d.6i,j.6i,1.63,1.9d,1.cc,1.b8,1.ep,1.l9,1.3v,1.82,1.82,1.cg,1.b2,1.6i,1.8h,1.5r,1.8h,1.cg,1.83," +
  "1.ad,1.9u,1.c1,1.ae,1.bt,1.aw,1.c8,1.bu,1.5r,1.66,1.bb,1.d0,1.bb,1.87,1.k9,1.gt,1.fl,1.gc,1.ho,1.er," +
  "1.dh,1.hl,1.ir,1.9c,1.8t,1.hd,1.e1,1.km,1.i7,1.i7,1.es,1.i7,1.hn,1.d2,1.fd,1.h8,1.gn,1.n5,1.g4,1.ev," +
  "1.fh,1.71,1.8h,1.6z,1.9t,1.a3,1.4m,1.cc,1.cj,1.9n,1.ci,1.9x,1.7g,1.as,1.cn,1.6v,1.6x,1.bg,1.6v,1.j1," +
  "1.d7,1.bc,1.b9,1.bp,1.9w,1.8s,1.8d,1.d8,1.cg,1.hg,1.by,1.cl,1.9k,1.7b,1.48,1.7c,1.cb,y.6i,1.62,1.du," +
  "1.as,1.ao,1.cg,1.48,1.bc,1.7n,1.k7,1.7o,1.c2,1.bb,1.8h,1.kv,1.99,1.8b,1.b2,1.6i,1.6i,1.5w,2.gi,1.5t," +
  "1.5g,1.6q,1.7h,1.c1,1.fi,1.fx,1.fa,1.93,1.gt,1.gt,1.gt,1.gt,1.gt,1.gt,1.lg,1.gc,1.er,1.er,1.er,1.er," +
  "1.9c,1.9c,1.9c,1.9c,1.ho,1.i7,1.i7,1.i7,1.i7,1.i7,1.i7,1.b3,1.i7,1.h8,1.h8,1.h8,1.h8,1.ev,1.f6,1.d7," +
  "1.cc,1.cc,1.cc,1.cc,1.cc,1.cc,1.gd,1.9n,1.9x,1.9x,1.9x,1.9x,1.6v,1.6v,1.6v,1.6v,1.b5,1.d7,1.bc,1.bc," +
  "1.bc,1.bc,1.bc,1.ay,1.bc,1.d8,1.d8,1.d8,1.d8,1.cl,1.bf,1.cl,1.gt,1.cc,1.gt,1.cc,1.gt,1.cf,1.gc,1.9n," +
  "1.gc,1.9n,1.gc,1.9n,1.gc,1.9n,1.ho,1.ci,1.ho,1.c4,1.er,1.9x,1.er,1.9x,1.er,1.9x,1.er,1.9x,1.er,1.9x," +
  "1.hl,1.as,1.hl,1.as,1.hl,1.as,1.hl,1.as,1.ir,1.cn,1.ir,1.cb,1.9c,1.6v,1.9c,1.6v,1.9c,1.6v,1.9c,1.6v," +
  "1.9c,1.6v,1.h7,1.cq,1.8t,1.6x,1.hd,1.bg,1.c0,1.e1,1.6v,1.e1,1.6v,1.e1,1.6v,1.e1,1.6v,1.e1,1.76,1.i7," +
  "1.d7,1.i7,1.d7,1.i7,1.d7,1.d7,1.i7,1.ci,1.i7,1.bc,1.i7,1.bc,1.i7,1.bc,1.mh,1.gv,1.hn,1.9w,1.hn,1.9w," +
  "1.hn,1.9w,1.d2,1.8s,1.d2,1.8s,1.d2,1.8s,1.d2,1.8s,1.fd,1.8d,1.fd,1.8d,1.fd,1.86,1.h8,1.d8,1.h8,1.d8," +
  "1.h8,1.d8,1.h8,1.d8,1.h8,1.d8,1.h8,1.d8,1.n5,1.hg,1.ev,1.cl,1.ev,1.fh,1.9k,1.fh,1.9k,1.fh,1.9k,1.6q," +
  "g.gf,3.7g,5.9c,9.i7,1.bc,e.h9,1.dk,t.gt,1.cc,1.9c,1.6v,1.i7,1.bc,1.h8,1.d8,1.h8,1.d8,1.h8,1.d8,1.h8," +
  "1.d8,1.h8,1.d8,6.lg,1.gd,3.hl,1.as,1.hd,1.bg,1.i7,1.bc,d.i7,1.d7,1.gt,1.cc,1.lg,1.gd,1.i7,1.bc,1.gt," +
  "1.cc,1.gt,1.cc,1.er,1.9x,1.er,1.9x,1.9c,1.6v,1.9c,1.6v,1.i7,1.bc,1.i7,1.bc,1.hn,1.9w,1.hn,1.9w,1.h8," +
  "1.d8,1.h8,1.d8,1.d2,1.8s,1.fd,1.8d,n.ev,1.cl,4.6x,d.h8,d.cc,8.a4,8.bt,7.6v,x.d8,1e.63,1.4h,2.5m,1.5g" +
  ",7.6n,1.66,3.7n,1.6v,d.6i,1.42,1.6x,1.6c,1.7l,1.7w,z.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1" +
  ".0,2.0,2.0,a.0,8.0,1.0,2.0,1.0,1.0,5.0,1.0,3.0,u.0,9.0,1o.h2,l.i0,j.cf,4.c9,1s.er,1.er,1.ir,1.df,1.g" +
  "c,1.d2,1.9c,1.9c,1.8t,1.nk,1.p6,1.iq,1.gx,1.j5,1.fp,1.jc,1.gt,1.ew,1.fl,1.df,1.ic,1.er,1.pw,1.dl,1.j" +
  "5,1.j5,1.gx,1.hw,1.km,1.ir,1.i7,1.jo,1.es,1.gc,1.fd,1.fp,1.jf,1.g4,1.jc,1.gh,1.ro,1.rm,1.gw,1.ng,1.e" +
  "r,1.fw,1.qa,1.fk,1.cc,1.bw,1.c1,1.9d,1.br,1.9x,1.jd,1.9e,1.d8,1.d8,1.cs,1.cg,1.ga,1.dd,1.bc,1.d7,1.b" +
  "9,1.9n,1.j1,1.cl,1.go,1.by,1.d8,1.c8,1.j1,1.j1,1.ax,1.gj,1.ax,1.ad,1.gw,1.bw,1.9x,1.9x,1.bv,1.9d,1.9" +
  "n,1.8s,1.6v,1.6v,1.6x,1.gj,1.hb,1.cb,1.cs,1.d8,1.cl,1.d8,3.ho,1.gq,7.mu,1.h6,7.i7,1.cn,1.gq,1.ch,l.j" +
  "i,1.d8,1.er,1.ac,1.es,1.b9,1.da,1.99,1.df,1.9d,1.fv,1.bh,1.pw,1.jd,1.dl,1.9e,1.ho,1.cs,1.ik,1.dj,1.g" +
  "x,1.c8,1.jp,1.dn,1.k3,1.de,1.mc,1.fr,3.jo,1.dd,1.gc,1.9n,1.fd,1.j1,1.ev,1.by,1.ev,1.by,1.gx,1.by,1.l" +
  "s,1.d6,1.gc,1.c8,1.gh,1.cv,1.gd,1.cn,1.id,1.cs,1.id,1.cs,1.9c,1.pw,1.jd,1.gx,1.cj,1.gt,1.cg,1.iq,1.d" +
  "0,1.ir,1.dd,1.gc,1.c8,1.km,1.gg,1.6v,1.gt,1.cc,1.gt,1.cc,1.lg,1.gd,1.er,1.9x,1.gf,1.a4,1.gf,1.a4,1.p" +
  "w,1.jd,1.dl,1.9e,1.dz,1.9u,1.j5,1.d8,1.j5,1.d8,1.i7,1.bc,1.i7,1.bc,1.i7,1.bc,1.fw,1.ad,1.fp,1.cl,1.f" +
  "p,1.cl,1.fp,1.cl,1.gh,1.c8,1.df,1.9d,1.ng,1.gj,1.df,1.a0,1.g4,1.by,1.g4,1.by,h.dl,1.9e,1.ht,1.c5,7.i" +
  "7,1.bp,1.n5,1.hg,7.jo,1.d7,1.gp,1.cn,1.iu,1.dr,5.ho,1.cg,1sg.el,34d.ho,1.ci,1.ho,1.ci,h.hl,1.as,3.ir" +
  ",1.cn,5.ir,1.cn,5.hd,1.bg,5.e1,1.6v,1.e1,1.6v,1.e1,1.6v,3.km,1.j1,1.km,1.j1,1.km,1.j1,1.i7,1.d7,1.i7" +
  ",1.d7,1.i7,1.d7,1.i7,1.d7,f.hn,1.9w,1.hn,1.9w,1.hn,1.9w,1.d2,1.8s,1.d2,1.8s,9.fd,1.8d,1.fd,1.8d,h.n5" +
  ",1.hg,1.n5,1.hg,1.n5,1.hg,9.ev,1.cl,3.fh,1.9k,4.8d,7.h4,2.gt,1.cc,1.gt,1.cc,1.gt,1.cc,1.gt,1.cc,1.gt" +
  ",1.cc,1.gt,1.cc,1.gt,1.cc,1.gt,1.cc,1.gt,1.cc,1.gt,1.cc,1.gt,1.cc,1.gt,1.cc,1.er,1.9x,1.er,1.9x,1.er" +
  ",1.9x,1.er,1.9x,1.er,1.9x,1.er,1.9x,1.er,1.9x,1.er,1.9x,1.9c,1.6v,1.9c,1.6v,1.i7,1.bc,1.i7,1.bc,1.i7" +
  ",1.bc,1.i7,1.bc,1.i7,1.bc,1.i7,1.bc,1.i7,1.bc,1.i7,1.bc,1.i7,1.bc,1.i7,1.bc,1.i7,1.bc,1.i7,1.bc,1.h8" +
  ",1.d8,1.h8,1.d8,1.h9,1.dk,1.h9,1.dk,1.h9,1.dk,1.h9,1.dk,1.h9,1.dk,1.ev,1.cl,1.ev,1.cl,1.ev,1.cl,1.ev" +
  ",1.cl,7b.eb,1.n2,1.dx,1.rt,1.99,1.6y,1.4n,1.dn,1.ji,1.5k,1.39,1.go,1.go,1.go,3.8h,1.8h,1.dm,1.eb,1.n" +
  "2,4.59,1.5a,1.3z,2.9s,1.9t,1.9s,2.92,1.a1,1.8y,4.ir,1.5t,1.go,1.go,6.5k,1.li,2.46,1.8f,6.7z,1.7x,8.n" +
  "t,1.cs,1.2p,r.66,1.go,3.go,d.7s,4.6q,1.6r,1.6w,1.6d,1.6w,1.7d,1.b2,3.42,1.41,1.8y,1.7s,1.6q,1.6i,1.6" +
  "i,1.6q,1.6r,1.6w,1.6d,1.6w,1.7d,4.41,1.41,j.du,3.as,2.e4,1.ce,3.g1,1.cm,1.f0,2.cj,3.ce,1.ee,2.av,1.d" +
  "u,3.cl,1.as,1.at,3.bp,2e.af,3.l5,1.kk,9.ht,2.kj,c.ds,19.gb,1.g3,1.gc,1.fy,1e.i1,1.c3,1.i1,1.c3,1.ka," +
  "1.c3,1.dc,1.dc,1.dc,1.dc,2x.cv,3.c4,a.kn,2.gw,1.b2,8.c1,4.kt,d.7t,t.e9,o.d0,4.b8,1.bc,mz.8e,1.8e,h.g" +
  "z,1.gz,3.gz,1.gz,5.gz,1.gz,3.gz,1.gz,5.8e,1.8e,3.8e,1.lb,4.lb,n.8d,l.gz,1.gz,w.u1,2.uc,s.mn,8c.jr,qd" +
  ".la,1.lb,ys.rs,njd.ef,2q.7b,1.67,ghg.ew,1.dd,1.e9,1.kt,1.lp,1.f3,1.gz,s9.go,6y.go,1.go,1.go";

const COURIER_PACKED =
  "d.y4,j.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,y.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,2.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,2.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,k.y4,3q.y4,1.y4" +
  ",1.y4,1.y4,s.y4,3z.y4,1.y4,h.y4,1.y4,1.y4,1.y4,1.y4,1.y4,21.0,32.y4,l.y4,j.y4,4.y4,5a8.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,31.y4,1.y4,7y.y4,2.y4,1.y4,4.y4,1.y4,1.y4,2.y4,1.y4,1.y4,2.y4,1.y4,1.y4,4.y4,a.y4,2.y" +
  "4,1.y4,6.y4,1.y4,a.y4,1c.y4,1b.y4,6.y4,3.y4,3a.y4,68.y4,d.y4,2.y4,1.y4,3.y4,5.y4,4.y4,d.y4,t.y4,o.y4" +
  ",4.y4,1.y4,o5.y4,1647.y4,1.y4";

const COURIER_BOLD_PACKED =
  "d.y4,j.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,y.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,2.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,2.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,k.y4,3q.y4,1.y4" +
  ",1.y4,1.y4,s.y4,3z.y4,1.y4,h.y4,1.y4,1.y4,1.y4,1.y4,1.y4,21.0,32.y4,l.y4,j.y4,4.y4,5a8.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,31.y4,1.y4,7y.y4,2.y4,1.y4,4.y4,1.y4,1.y4,2.y4,1.y4,1.y4,2.y4,1.y4,1.y4,4.y4,a.y4,2.y" +
  "4,1.y4,6.y4,1.y4,a.y4,1c.y4,1b.y4,6.y4,3.y4,3a.y4,68.y4,d.y4,2.y4,1.y4,3.y4,5.y4,4.y4,d.y4,t.y4,o.y4" +
  ",4.y4,1.y4,o5.y4,1647.y4,1.y4";

const COURIER_ITALIC_PACKED =
  "d.y4,j.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,y.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,2.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,2.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,k.y4,3q.y4,1.y4" +
  ",1.y4,1.y4,s.y4,3z.y4,1.y4,h.y4,1.y4,1.y4,1.y4,1.y4,1.y4,21.0,32.y4,l.y4,j.y4,4.y4,5a8.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,31.y4,1.y4,7y.y4,2.y4,1.y4,4.y4,1.y4,1.y4,2.y4,1.y4,1.y4,2.y4,1.y4,1.y4,4.y4,a.y4,2.y" +
  "4,1.y4,6.y4,1.y4,a.y4,1c.y4,1b.y4,6.y4,3.y4,3a.y4,68.y4,d.y4,2.y4,1.y4,3.y4,5.y4,4.y4,d.y4,t.y4,o.y4" +
  ",4.y4,1.y4,o5.y4,1647.y4,1.y4";

const COURIER_BOLD_ITALIC_PACKED =
  "d.y4,j.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,y.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,2.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,2.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,1.y4,k.y4,3q.y4,1.y4" +
  ",1.y4,1.y4,s.y4,3z.y4,1.y4,h.y4,1.y4,1.y4,1.y4,1.y4,1.y4,21.0,32.y4,l.y4,j.y4,4.y4,5a8.y4,1.y4,1.y4," +
  "1.y4,1.y4,1.y4,31.y4,1.y4,7y.y4,2.y4,1.y4,4.y4,1.y4,1.y4,2.y4,1.y4,1.y4,2.y4,1.y4,1.y4,4.y4,a.y4,2.y" +
  "4,1.y4,6.y4,1.y4,a.y4,1c.y4,1b.y4,6.y4,3.y4,3a.y4,68.y4,d.y4,2.y4,1.y4,3.y4,5.y4,4.y4,d.y4,t.y4,o.y4" +
  ",4.y4,1.y4,o5.y4,1647.y4,1.y4";

export const FONT_METRICS: Readonly<Record<BundledFontFace, GeneratedFontMetrics>> = {
  garamond: {
    unitsPerEm: 1000,
    fallbackAdvance: 508,
    advances: decode(GARAMOND_PACKED),
    ascent: 0.924,
  },
  garamond_bold: {
    unitsPerEm: 1000,
    fallbackAdvance: 516,
    advances: decode(GARAMOND_BOLD_PACKED),
    ascent: 0.924,
  },
  garamond_italic: {
    unitsPerEm: 1000,
    fallbackAdvance: 465,
    advances: decode(GARAMOND_ITALIC_PACKED),
    ascent: 0.924,
  },
  garamond_bold_italic: {
    unitsPerEm: 1000,
    fallbackAdvance: 474,
    advances: decode(GARAMOND_BOLD_ITALIC_PACKED),
    ascent: 0.924,
  },
  courier: {
    unitsPerEm: 2048,
    fallbackAdvance: 1225,
    advances: decode(COURIER_PACKED),
    ascent: 0.78125,
  },
  courier_bold: {
    unitsPerEm: 2048,
    fallbackAdvance: 1225,
    advances: decode(COURIER_BOLD_PACKED),
    ascent: 0.78125,
  },
  courier_italic: {
    unitsPerEm: 2048,
    fallbackAdvance: 1225,
    advances: decode(COURIER_ITALIC_PACKED),
    ascent: 0.78125,
  },
  courier_bold_italic: {
    unitsPerEm: 2048,
    fallbackAdvance: 1225,
    advances: decode(COURIER_BOLD_ITALIC_PACKED),
    ascent: 0.78125,
  },
};
