// Generated by scripts/generate-font-metrics.mjs — do not edit by hand.
// Advance widths of GeistVF.woff's 645 covered BMP codepoints, in font units
// (unitsPerEm 1000) — the TextBox wrap engine's measuring stick (DESIGN.md §3.3).
// Encoding: "<codepoint delta base36>.<advance base36>" entries joined by ",",
// codepoints ascending — decoded into a Map at module load.

export const GEIST_UNITS_PER_EM = 1000;

/** Mean advance over the covered codepoints — charged for uncovered chars. */
export const GEIST_FALLBACK_ADVANCE = 579;

const PACKED =
  "w.6y,1.65,1.9w,1.da,1.i0,1.lc,1.h8,1.56,1.82,1.82,1.c4,1.fu,1.5r,1.bt,1.5r,1.dc,1.in,1.ao,1.h7,1.h1," +
  "1.hn,1.he,1.hc,1.g8,1.gs,1.hc,1.89,1.89,1.f9,1.ic,1.fd,1.fp,1.pe,1.im,1.iw,1.jr,1.ji,1.gr,1.ge,1.jo," +
  "1.jt,1.7i,1.gl,1.i4,1.g4,1.od,1.kn,1.kr,1.i2,1.kl,1.io,1.i0,1.g2,1.j5,1.il,1.pb,1.hi,1.hi,1.f2,1.9z," +
  "1.d9,1.9z,1.b4,1.fn,1.72,1.fu,1.gm,1.fc,1.gm,1.fr,1.b2,1.gl,1.g5,1.6s,1.78,1.ge,1.7w,1.od,1.g5,1.g3," +
  "1.gm,1.gm,1.am,1.eq,1.az,1.fz,1.ew,1.mr,1.g9,1.ex,1.f9,1.b9,1.7b,1.b9,1.ex,y.6y,1.65,1.fc,1.h3,1.ga," +
  "1.hi,1.7b,1.fh,1.9w,1.n8,1.bd,1.ex,1.dh,2.gq,1.a2,1.ay,1.fu,1.9u,1.ac,1.72,1.gh,1.gd,1.5r,1.8z,1.76," +
  "1.bc,1.ex,1.lo,1.mx,1.md,1.fp,1.im,1.im,1.im,1.im,1.im,1.im,1.r2,1.jr,1.gr,1.gr,1.gr,1.gr,1.7i,1.7i," +
  "1.7i,1.7i,1.ly,1.kn,1.kr,1.kr,1.kr,1.kr,1.kr,1.di,1.kv,1.j5,1.j5,1.j5,1.j5,1.hi,1.h8,1.ge,1.fu,1.fu," +
  "1.fu,1.fu,1.fu,1.fu,1.pw,1.fc,1.fr,1.fr,1.fr,1.fr,1.6s,1.6s,1.6s,1.6s,1.g3,1.g5,1.g3,1.g3,1.g3,1.g3," +
  "1.g3,1.fu,1.fo,1.fz,1.fz,1.fz,1.fz,1.ex,1.gm,1.ex,1.im,1.fu,1.im,1.fu,1.im,1.fu,1.jr,1.fc,1.jr,1.fc," +
  "1.jr,1.fc,1.jr,1.fc,1.ji,1.gm,1.ly,1.i3,1.gr,1.fr,3.gr,1.fr,1.gr,1.fr,1.gr,1.fr,1.jo,1.gl,1.jo,1.gl," +
  "1.jo,1.gl,1.jo,1.gl,1.jt,1.g5,1.lc,1.gu,1.7i,1.6s,1.7i,1.6s,3.7i,1.6s,1.7i,1.6s,1.o3,1.dq,1.gl,1.78," +
  "1.i4,1.ge,2.g4,1.7w,1.g4,1.7w,1.g4,1.7w,3.gy,1.89,1.kn,1.g5,1.kn,1.g5,1.kn,1.g5,2.ki,1.g5,1.kr,1.g3," +
  "3.kr,1.g3,1.u6,1.qs,1.io,1.am,1.io,1.am,1.io,1.am,1.i0,1.eq,1.i0,1.eq,1.i0,1.eq,1.i0,1.eq,1.g2,1.az," +
  "1.g2,1.az,1.g2,1.az,1.j5,1.fz,1.j5,1.fz,1.j5,1.fz,1.j5,1.fz,1.j5,1.fz,1.j5,1.fz,1.pb,1.mr,1.hi,1.ex," +
  "1.hi,1.f2,1.f9,1.f2,1.f9,1.f2,1.f9,h.k1,3.ea,1n.im,1.fu,m.ky,1.hl,1.jo,1.gl,1.i4,1.ge,1b.i0,1.eq,1.g" +
  "2,1.az,s.78,y.fr,2o.6y,3.5q,a.a8,1.a8,1.53,g.ad,1.52,1.7q,1.7j,1.bd,1.ap,z.0,1.0,1.0,1.0,1.0,2.0,1.0" +
  ",1.0,2.0,1.0,1.0,6.0,k.0,1.0,1.0,d.0,2u.im,e.kj,i.fw,5.ia,1s.gr,1.gr,1.ln,1.gd,1.kh,1.i0,1.7i,1.7i,1" +
  ".gl,1.w3,1.ud,1.ln,1.i2,2.f2,1.jj,1.im,1.ic,1.iw,1.gd,1.mc,1.gr,1.qf,1.i5,1.ki,1.ki,1.i2,1.l9,1.od,1" +
  ".jj,1.kr,1.jj,1.i2,1.jh,1.g2,1.f2,1.nb,1.hh,1.le,1.i4,1.pi,1.rd,1.kj,1.nr,1.ic,1.kh,1.rm,1.it,1.fz,1" +
  ".gp,1.gg,1.dk,1.j5,1.fr,1.nw,1.ev,1.fx,1.fx,1.gg,1.ir,1.jy,1.g2,1.g3,1.g3,1.gm,1.fc,1.fl,1.ex,1.hz,1" +
  ".g9,1.i6,1.gp,1.m2,1.o0,1.i0,1.m2,1.g7,1.fv,1.lw,1.gd,1.fr,1.fr,1.h4,1.dk,1.fv,1.eq,1.6s,1.6s,1.78,1" +
  ".s6,1.ph,1.gu,1.gg,1.fx,1.ex,1.g3,3.kq,1.ix,7.jm,1.jm,7.kr,1.g3,1.k4,1.gb,r.ee,1.bz,1.hu,1.ex,3.qy,1" +
  ".o2,3.ih,1.go,7.ku,1.ia,b.hi,1.ew,1.hi,1.ew,1.ih,1.h4,3.jl,1.ig,3.i4,1.g5,5.7i,f.7g,9.k1,1.fr,9.ki,1" +
  ".fx,5.kr,1.g3,5.f2,1.ex,1u8.hs,34x.jo,1.gl,2n.pb,1.mr,1.pb,1.mr,1.pb,1.mr,p.j9,u.gr,1.fr,1h.hi,1.ex," +
  "5.hi,1.ex,7u.gl,1.pd,4.5v,1.5v,1.5v,2.ag,1.ag,1.ag,2.fu,1.fu,1.86,4.g1,a.uc,2.6y,1.ak,6.9b,1.9b,a.go" +
  ",18.aw,4.az,1.9w,1.9v,1.97,1.ac,1.a0,7.aw,1.76,1.9u,1.ac,1.az,1.9w,1.9v,1.97,1.ac,1.a0,x.lh,2.kf,8.i" +
  "p,5.iv,4.jz,22.gg,f.ua,1.gq,b.oq,1d.mb,1.nz,1.ni,6.n9,1.o0,1.np,1.m6,1e.mg,1.k0,1.mg,1.k0,1.t0,1.k0," +
  "1.hh,1.hh,1.hi,1.hi,4.ib,c.if,1.if,6.im,1.im,2.im,1.ir,1.im,1b.iv,1.iv,2.m6,r.gl,4.i3,9.h4,2.ep,1.fu" +
  ",8.gy,4.nd,d.ai,t.ex,o.fu,4.fu,1.fu,a1.ns,1p.go,1.go,2c.n4,1.n4,1.n4,1.n4,1.n4,1.n4,1.n4,1.n4,1.n4,3" +
  "m.n4,l.n4,4z.nx,1.nx,3.mv,1.mv,5.nx,1.nx,3.mv,1.mv,9.ez,1.no,1.no,3.no,2y.n4,1.n4,8s.n4,1.n4,1.n4,1." +
  "n4,1.n4,1.n4,1.n4,1.n4,1.n4,1ol.ac,5.9y,1.9y,1.el,1.el,1.b0,1.b0,1.b1,1.b1,1.a8,1.a8,3.b1,1.b1,1.9z," +
  "1.9z,5.ns,nlb.56,1.56,g37.go,ea.hu,1.ie";

function decode(packed: string): ReadonlyMap<number, number> {
  const map = new Map<number, number>();
  let cp = 0;
  for (const entry of packed.split(",")) {
    const dot = entry.indexOf(".");
    cp += parseInt(entry.slice(0, dot), 36);
    map.set(cp, parseInt(entry.slice(dot + 1), 36));
  }
  return map;
}

/** BMP codepoint → advance width in font units. */
export const GEIST_ADVANCES: ReadonlyMap<number, number> = decode(PACKED);
